### ISSUE TITLE
Tareas pendientes eCar

### ISSUE THREAD

**Issue by jlblancoc** [ual-arm-ros-pkg/ual-ecar-ros-pkg#2]
* Nivel "físico" / cableado:
 * [x] Conexión nueva fuente de 24V.
 * [x] Conexión filtros antes de las fuentes CC-CC.
 * [x] Separación de la alimentación del monitor del resto de sensores.
 * [x] Revisar el "Pedal Interlock" y su programación en el firmware.
 * [x] Cambiar etiqueta del hub usb : "Velodyne"->"Novatel"
 * [x] Fijar fuentes y cajas negras del maletero con tornillos a perfiles (hay que comprar? @torresmoreno ?)

* LibreDAQ: Con idea de que acabe sustituyendo a: Phidges encoders; y (sólo si no se consigue echar a andar en un tiempo prudencial) a la PCB de medición de baterías:
  * [x] Soldar 1/2 placas ADC.
  * [x] Montar caja con conectores "industriales" y cables hacia placas interiores.
  * [x] Actualizar firmware para adaptarlo a configuración usada en el coche (número de slots ocupados).
  * [x] Hacer nodo ROS! (La lib c++ ya está y funciona).

* Nivel firmware:
 * [x] Crear un Offset configurable desde ROS (JL: del ángulo del volante, entiendo?) @FranciscoJManasAlvarez 
 * [x] Cambiar el tipo de la variable del encoder en el controlador de float a int32.
 * [x] Crear firmware del freno.
 * [x] Hacer funcionar el firmware para la lectura de las baterías.

* Nivel ROS: 
 * [x] Instalar nodo del IMU XSENS
 * [x] Crear un Offset configurable para la recalibración de la dirección a partir de los valores de los encoders de las ruedas traseras.
 * [x] mrpt_sensors: tiene su propia TODO list [aqui](https://github.com/mrpt-ros-pkg/mrpt_sensors/issues/1). Asignado: @jlblancoc

**Comment by FranciscoJManasAlvarez** [comment]
Fuente nueva instalada y se añaden tareas para el freno

**Comment by jlblancoc** [comment]
Añado sección LibreDAQ, y un par de comentarios.

**Comment by jlblancoc** [comment]
Ya he marcado como hechas todas las tareas que se habían hecho, y para el resto, he creado un issue por cada una, para llevar mejor el control. Recomiendo instalar en chrome el ZenHub para ver las tareas ordenadas por prioridades. 

Cierro éste!
